export const products = [
  {
    id: "1",
    title: "Product 1",
    description: "This is the first product",
    price: 10,
    imageUrl: "https://picsum.photos/200/300",
    category: "Category 1",
    createdAt: new Date(),
  },
  {
    id: "2",
    title: "Product 2",
    description: "This is the second product",
    price: 20,
    imageUrl: "https://picsum.photos/200/300",
    category: "Category 1",
    createdAt: new Date(),
  },
  {
    id: "3",
    title: "Product 3",
    description: "This is the third product",
    price: 30,
    imageUrl: "https://picsum.photos/200/300",
    category: "Category 1",
    createdAt: new Date(),
  },
  {
    id: "4",
    title: "Product 4",
    description: "This is the fourth product",
    price: 40,
    imageUrl: "https://picsum.photos/200/300",
    category: "Category 1",
    createdAt: new Date(),
  },
  {
    id: "5",
    title: "Product 5",
    description: "This is the fifth product",
    price: 50,
    imageUrl: "https://picsum.photos/200/300",
    category: "Category 1",
    createdAt: new Date(),
  },
  {
    id: "6",
    title: "Product 6",
    description: "This is the sixth product",
    price: 60,
    imageUrl: "https://picsum.photos/200/300",
    category: "Category 1",
    createdAt: new Date(),
  },
];
